// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSpreadsheet() {
  return window['go']['main']['App']['OpenSpreadsheet']();
}

export function OpenSpreadsheetFromPath(arg1) {
  return window['go']['main']['App']['OpenSpreadsheetFromPath'](arg1);
}
